import { useState } from 'react';
import { Search, Plus, MessageCircle, ChevronRight } from 'lucide-react';
import { Avatar, Empty } from './Shared.jsx';
import { time } from '../api.js';
export default function Sidebar({ conversations, selectedId, onSelect, onFriends, loading }) {
  const [query, setQuery] = useState('');
  const filtered = conversations.filter(c => c.user.username.toLowerCase().includes(query.toLowerCase()));
  return <aside className="sidebar"><div className="sidebar-title"><h2>Your inbox <span>{conversations.length}</span></h2><button className="icon-button tinted" aria-label="Find a friend to message" onClick={onFriends}><Plus size={19}/></button></div><label className="search-field"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search conversations" aria-label="Search conversations"/></label><div className="conversation-list">{loading ? <p className="loading">Loading conversations…</p> : !filtered.length ? <Empty icon={MessageCircle} title={query ? 'No matches' : 'Start a conversation'}>{query ? 'Try a different name.' : 'Find a classmate and add them as a friend.'}</Empty> : filtered.map(c => <button key={c.id} className={`conversation-item ${c.id === selectedId ? 'selected' : ''}`} onClick={() => onSelect(c)}><Avatar user={c.user}/><span className="conversation-info"><span className="conversation-top"><strong>{c.user.username}</strong><time>{time(c.lastMessage?.createdAt)}</time></span><span className="conversation-bottom"><span>{c.lastMessage?.text || (c.lastMessage?.media?.kind === 'AUDIO' ? 'Voice message' : c.lastMessage?.media ? 'Photo' : 'Say hello 👋')}</span>{c.unreadCount > 0 && <b className="unread">{c.unreadCount > 99 ? '99+' : c.unreadCount}</b>}</span></span></button>)}</div><button className="find-friends" onClick={onFriends}><span className="friend-plus"><Plus size={20}/></span><span><strong>Meet someone new</strong><small>Explore your community</small></span><ChevronRight size={17}/></button></aside>;
}
